/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type COULDNOTPERFORMREQUESTContext = {};

export type CouldNotPerformRequest = {
    context?: COULDNOTPERFORMREQUESTContext | undefined;
    errorCode?: string | undefined;
    message?: string | undefined;
    path: string;
    statusCode?: number | undefined;
    timestamp: string;
};

/** @internal */
export namespace COULDNOTPERFORMREQUESTContext$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<COULDNOTPERFORMREQUESTContext, z.ZodTypeDef, Inbound> =
        z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, COULDNOTPERFORMREQUESTContext> =
        z.object({});
}

/** @internal */
export namespace CouldNotPerformRequest$ {
    export type Inbound = {
        context?: COULDNOTPERFORMREQUESTContext$.Inbound | undefined;
        errorCode?: string | undefined;
        message?: string | undefined;
        path: string;
        statusCode?: number | undefined;
        timestamp: string;
    };

    export const inboundSchema: z.ZodType<CouldNotPerformRequest, z.ZodTypeDef, Inbound> = z
        .object({
            context: z.lazy(() => COULDNOTPERFORMREQUESTContext$.inboundSchema).optional(),
            errorCode: z.string().default("COULD_NOT_PERFORM_REQUEST"),
            message: z.string().default("Unexpected error occurred performing the request."),
            path: z.string(),
            statusCode: z.number().default(500),
            timestamp: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.context === undefined ? null : { context: v.context }),
                errorCode: v.errorCode,
                message: v.message,
                path: v.path,
                statusCode: v.statusCode,
                timestamp: v.timestamp,
            };
        });

    export type Outbound = {
        context?: COULDNOTPERFORMREQUESTContext$.Outbound | undefined;
        errorCode: string;
        message: string;
        path: string;
        statusCode: number;
        timestamp: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CouldNotPerformRequest> = z
        .object({
            context: z.lazy(() => COULDNOTPERFORMREQUESTContext$.outboundSchema).optional(),
            errorCode: z.string().default("COULD_NOT_PERFORM_REQUEST"),
            message: z.string().default("Unexpected error occurred performing the request."),
            path: z.string(),
            statusCode: z.number().default(500),
            timestamp: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.context === undefined ? null : { context: v.context }),
                errorCode: v.errorCode,
                message: v.message,
                path: v.path,
                statusCode: v.statusCode,
                timestamp: v.timestamp,
            };
        });
}
