/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AwsKmsCredentialsDto } from "./awskmscredentialsdto";
import { Expose, Type } from "class-transformer";

export class CreateKmsDtoMetadata extends SpeakeasyBase {}

export enum CreateKmsDtoProvider {
    Aws = "AWS",
    Vault = "Vault",
}

export class CreateKmsDto extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "credentials" })
    @Type(() => AwsKmsCredentialsDto)
    credentials?: AwsKmsCredentialsDto;

    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => CreateKmsDtoMetadata)
    metadata?: CreateKmsDtoMetadata;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "provider" })
    provider: CreateKmsDtoProvider;

    @SpeakeasyMetadata()
    @Expose({ name: "secret" })
    secret: string;
}
