/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum DirectoryContentType {
    Directory = "directory",
    File = "file",
}

export type DirectoryContent = {
    cid: string;
    name: string;
    size: number;
    type?: DirectoryContentType | undefined;
};

/** @internal */
export const DirectoryContentType$: z.ZodNativeEnum<typeof DirectoryContentType> =
    z.nativeEnum(DirectoryContentType);

/** @internal */
export namespace DirectoryContent$ {
    export type Inbound = {
        cid: string;
        name: string;
        size: number;
        type?: DirectoryContentType | undefined;
    };

    export const inboundSchema: z.ZodType<DirectoryContent, z.ZodTypeDef, Inbound> = z
        .object({
            cid: z.string(),
            name: z.string(),
            size: z.number(),
            type: DirectoryContentType$.optional(),
        })
        .transform((v) => {
            return {
                cid: v.cid,
                name: v.name,
                size: v.size,
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });

    export type Outbound = {
        cid: string;
        name: string;
        size: number;
        type?: DirectoryContentType | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DirectoryContent> = z
        .object({
            cid: z.string(),
            name: z.string(),
            size: z.number(),
            type: DirectoryContentType$.optional(),
        })
        .transform((v) => {
            return {
                cid: v.cid,
                name: v.name,
                size: v.size,
                ...(v.type === undefined ? null : { type: v.type }),
            };
        });
}
