/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type INVALIDARGUMENTContext = {};

export type InvalidArgument = {
    context?: INVALIDARGUMENTContext | undefined;
    errorCode?: string | undefined;
    message?: string | undefined;
    path: string;
    statusCode?: number | undefined;
    timestamp: string;
};

/** @internal */
export namespace INVALIDARGUMENTContext$ {
    export type Inbound = {};

    export const inboundSchema: z.ZodType<INVALIDARGUMENTContext, z.ZodTypeDef, Inbound> = z.object(
        {}
    );

    export type Outbound = {};

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, INVALIDARGUMENTContext> =
        z.object({});
}

/** @internal */
export namespace InvalidArgument$ {
    export type Inbound = {
        context?: INVALIDARGUMENTContext$.Inbound | undefined;
        errorCode?: string | undefined;
        message?: string | undefined;
        path: string;
        statusCode?: number | undefined;
        timestamp: string;
    };

    export const inboundSchema: z.ZodType<InvalidArgument, z.ZodTypeDef, Inbound> = z
        .object({
            context: z.lazy(() => INVALIDARGUMENTContext$.inboundSchema).optional(),
            errorCode: z.string().default("INVALID_ARGUMENT"),
            message: z.string().default("Some params are invalid."),
            path: z.string(),
            statusCode: z.number().default(400),
            timestamp: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.context === undefined ? null : { context: v.context }),
                errorCode: v.errorCode,
                message: v.message,
                path: v.path,
                statusCode: v.statusCode,
                timestamp: v.timestamp,
            };
        });

    export type Outbound = {
        context?: INVALIDARGUMENTContext$.Outbound | undefined;
        errorCode: string;
        message: string;
        path: string;
        statusCode: number;
        timestamp: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, InvalidArgument> = z
        .object({
            context: z.lazy(() => INVALIDARGUMENTContext$.outboundSchema).optional(),
            errorCode: z.string().default("INVALID_ARGUMENT"),
            message: z.string().default("Some params are invalid."),
            path: z.string(),
            statusCode: z.number().default(400),
            timestamp: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.context === undefined ? null : { context: v.context }),
                errorCode: v.errorCode,
                message: v.message,
                path: v.path,
                statusCode: v.statusCode,
                timestamp: v.timestamp,
            };
        });
}
