/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type SignMessageDto = {
    message: string;
};

/** @internal */
export namespace SignMessageDto$ {
    export const inboundSchema: z.ZodType<SignMessageDto, z.ZodTypeDef, unknown> = z
        .object({
            message: z.string(),
        })
        .transform((v) => {
            return {
                message: v.message,
            };
        });

    export type Outbound = {
        message: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SignMessageDto> = z
        .object({
            message: z.string(),
        })
        .transform((v) => {
            return {
                message: v.message,
            };
        });
}
