/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ExplorerApiDto, ExplorerApiDto$ } from "./explorerapidto";
import { GasPriceRecommendationDto, GasPriceRecommendationDto$ } from "./gaspricerecommendationdto";
import * as z from "zod";

export type UpdateNetworkDto = {
    blockchain?: string | undefined;
    chainId?: number | undefined;
    confirmationBlocks?: number | undefined;
    decimal?: number | undefined;
    displayName?: string | undefined;
    eip1159?: boolean | undefined;
    enableExternalWallet?: boolean | undefined;
    enableListener?: boolean | undefined;
    enableRelayer?: boolean | undefined;
    explorerApi?: ExplorerApiDto | undefined;
    explorerUrl?: string | undefined;
    gasPriceRecommendation?: GasPriceRecommendationDto | undefined;
    logo?: string | undefined;
    name?: string | undefined;
    symbol?: string | undefined;
    testnet?: boolean | undefined;
    verifyBlockIntegrity?: boolean | undefined;
    verifyTxIntegrity?: boolean | undefined;
};

/** @internal */
export namespace UpdateNetworkDto$ {
    export const inboundSchema: z.ZodType<UpdateNetworkDto, z.ZodTypeDef, unknown> = z.object({
        blockchain: z.string().optional(),
        chainId: z.number().optional(),
        confirmationBlocks: z.number().optional(),
        decimal: z.number().optional(),
        displayName: z.string().optional(),
        eip1159: z.boolean().optional(),
        enableExternalWallet: z.boolean().optional(),
        enableListener: z.boolean().optional(),
        enableRelayer: z.boolean().optional(),
        explorerApi: ExplorerApiDto$.inboundSchema.optional(),
        explorerUrl: z.string().optional(),
        gasPriceRecommendation: GasPriceRecommendationDto$.inboundSchema.optional(),
        logo: z.string().optional(),
        name: z.string().optional(),
        symbol: z.string().optional(),
        testnet: z.boolean().optional(),
        verifyBlockIntegrity: z.boolean().optional(),
        verifyTxIntegrity: z.boolean().optional(),
    });

    export type Outbound = {
        blockchain?: string | undefined;
        chainId?: number | undefined;
        confirmationBlocks?: number | undefined;
        decimal?: number | undefined;
        displayName?: string | undefined;
        eip1159?: boolean | undefined;
        enableExternalWallet?: boolean | undefined;
        enableListener?: boolean | undefined;
        enableRelayer?: boolean | undefined;
        explorerApi?: ExplorerApiDto$.Outbound | undefined;
        explorerUrl?: string | undefined;
        gasPriceRecommendation?: GasPriceRecommendationDto$.Outbound | undefined;
        logo?: string | undefined;
        name?: string | undefined;
        symbol?: string | undefined;
        testnet?: boolean | undefined;
        verifyBlockIntegrity?: boolean | undefined;
        verifyTxIntegrity?: boolean | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateNetworkDto> = z.object({
        blockchain: z.string().optional(),
        chainId: z.number().optional(),
        confirmationBlocks: z.number().optional(),
        decimal: z.number().optional(),
        displayName: z.string().optional(),
        eip1159: z.boolean().optional(),
        enableExternalWallet: z.boolean().optional(),
        enableListener: z.boolean().optional(),
        enableRelayer: z.boolean().optional(),
        explorerApi: ExplorerApiDto$.outboundSchema.optional(),
        explorerUrl: z.string().optional(),
        gasPriceRecommendation: GasPriceRecommendationDto$.outboundSchema.optional(),
        logo: z.string().optional(),
        name: z.string().optional(),
        symbol: z.string().optional(),
        testnet: z.boolean().optional(),
        verifyBlockIntegrity: z.boolean().optional(),
        verifyTxIntegrity: z.boolean().optional(),
    });
}
