/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class UpdatePinDtoMetadata extends SpeakeasyBase {}

export class UpdatePinDto extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "metadata" })
    @Type(() => UpdatePinDtoMetadata)
    metadata?: UpdatePinDtoMetadata;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}
