/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { BadRequestException, BadRequestException$ } from "./badrequestexception";
import { CouldNotCancelWebhook, CouldNotCancelWebhook$ } from "./couldnotcancelwebhook";
import { CouldNotFindResource, CouldNotFindResource$ } from "./couldnotfindresource";
import * as z from "zod";

export type CancelWebhookWebhookResponseResponseBody = CouldNotCancelWebhook;

export type CancelWebhookWebhookResponseBody = CouldNotFindResource;

export type CancelWebhookResponseBody = BadRequestException;

/** @internal */
export namespace CancelWebhookWebhookResponseResponseBody$ {
    export type Inbound = CouldNotCancelWebhook$.Inbound;

    export type Outbound = CouldNotCancelWebhook$.Outbound;
    export const inboundSchema: z.ZodType<
        CancelWebhookWebhookResponseResponseBody,
        z.ZodTypeDef,
        Inbound
    > = CouldNotCancelWebhook$.inboundSchema;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CancelWebhookWebhookResponseResponseBody
    > = CouldNotCancelWebhook$.outboundSchema;
}

/** @internal */
export namespace CancelWebhookWebhookResponseBody$ {
    export type Inbound = CouldNotFindResource$.Inbound;

    export type Outbound = CouldNotFindResource$.Outbound;
    export const inboundSchema: z.ZodType<CancelWebhookWebhookResponseBody, z.ZodTypeDef, Inbound> =
        CouldNotFindResource$.inboundSchema;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CancelWebhookWebhookResponseBody
    > = CouldNotFindResource$.outboundSchema;
}

/** @internal */
export namespace CancelWebhookResponseBody$ {
    export type Inbound = BadRequestException$.Inbound;

    export type Outbound = BadRequestException$.Outbound;
    export const inboundSchema: z.ZodType<CancelWebhookResponseBody, z.ZodTypeDef, Inbound> =
        BadRequestException$.inboundSchema;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CancelWebhookResponseBody> =
        BadRequestException$.outboundSchema;
}
