/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";

export type SchemasCOULDNOTBROADCASTContext = {};

export type CouldNotBroadcastData = {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse1?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse2?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse3?: Response | undefined;
  context?: SchemasCOULDNOTBROADCASTContext | null | undefined;
  errorCode?: string;
  message?: string;
  path: string;
  statusCode?: number;
  timestamp: string;
};

export class CouldNotBroadcast extends Error {
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse1?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse2?: Response | undefined;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse3?: Response | undefined;
  context?: SchemasCOULDNOTBROADCASTContext | null | undefined;
  errorCode?: string;
  path: string;
  statusCode?: number;
  timestamp: string;

  /** The original data that was passed to this error instance. */
  data$: CouldNotBroadcastData;

  constructor(err: CouldNotBroadcastData) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message);
    this.data$ = err;

    if (err.rawResponse != null) this.rawResponse = err.rawResponse;
    if (err.rawResponse1 != null) this.rawResponse1 = err.rawResponse1;
    if (err.rawResponse2 != null) this.rawResponse2 = err.rawResponse2;
    if (err.rawResponse3 != null) this.rawResponse3 = err.rawResponse3;
    if (err.context != null) this.context = err.context;
    if (err.errorCode != null) this.errorCode = err.errorCode;
    this.path = err.path;
    if (err.statusCode != null) this.statusCode = err.statusCode;
    this.timestamp = err.timestamp;

    this.name = "CouldNotBroadcast";
  }
}

/** @internal */
export const SchemasCOULDNOTBROADCASTContext$inboundSchema: z.ZodType<
  SchemasCOULDNOTBROADCASTContext,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type SchemasCOULDNOTBROADCASTContext$Outbound = {};

/** @internal */
export const SchemasCOULDNOTBROADCASTContext$outboundSchema: z.ZodType<
  SchemasCOULDNOTBROADCASTContext$Outbound,
  z.ZodTypeDef,
  SchemasCOULDNOTBROADCASTContext
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SchemasCOULDNOTBROADCASTContext$ {
  /** @deprecated use `SchemasCOULDNOTBROADCASTContext$inboundSchema` instead. */
  export const inboundSchema = SchemasCOULDNOTBROADCASTContext$inboundSchema;
  /** @deprecated use `SchemasCOULDNOTBROADCASTContext$outboundSchema` instead. */
  export const outboundSchema = SchemasCOULDNOTBROADCASTContext$outboundSchema;
  /** @deprecated use `SchemasCOULDNOTBROADCASTContext$Outbound` instead. */
  export type Outbound = SchemasCOULDNOTBROADCASTContext$Outbound;
}

/** @internal */
export const CouldNotBroadcast$inboundSchema: z.ZodType<
  CouldNotBroadcast,
  z.ZodTypeDef,
  unknown
> = z.object({
  RawResponse: z.instanceof(Response).optional(),
  RawResponse1: z.instanceof(Response).optional(),
  RawResponse2: z.instanceof(Response).optional(),
  RawResponse3: z.instanceof(Response).optional(),
  context: z.nullable(
    z.lazy(() => SchemasCOULDNOTBROADCASTContext$inboundSchema),
  ).optional(),
  errorCode: z.string().default("COULD_NOT_BROADCAST"),
  message: z.string().default("Could not broadcast this transaction."),
  path: z.string(),
  statusCode: z.number().default(500),
  timestamp: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "RawResponse": "rawResponse",
      "RawResponse1": "rawResponse1",
      "RawResponse2": "rawResponse2",
      "RawResponse3": "rawResponse3",
    });

    return new CouldNotBroadcast(remapped);
  });

/** @internal */
export type CouldNotBroadcast$Outbound = {
  RawResponse?: never | undefined;
  RawResponse1?: never | undefined;
  RawResponse2?: never | undefined;
  RawResponse3?: never | undefined;
  context?: SchemasCOULDNOTBROADCASTContext$Outbound | null | undefined;
  errorCode?: string;
  message?: string;
  path: string;
  statusCode?: number;
  timestamp: string;
};

/** @internal */
export const CouldNotBroadcast$outboundSchema: z.ZodType<
  CouldNotBroadcast$Outbound,
  z.ZodTypeDef,
  CouldNotBroadcast
> = z.instanceof(CouldNotBroadcast)
  .transform(v => v.data$)
  .pipe(
    z.object({
      rawResponse: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
      }).optional(),
      rawResponse1: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
      }).optional(),
      rawResponse2: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
      }).optional(),
      rawResponse3: z.instanceof(Response).transform(() => {
        throw new Error("Response cannot be serialized");
      }).optional(),
      context: z.nullable(
        z.lazy(() => SchemasCOULDNOTBROADCASTContext$outboundSchema),
      ).optional(),
      errorCode: z.string().default("COULD_NOT_BROADCAST"),
      message: z.string().default("Could not broadcast this transaction."),
      path: z.string(),
      statusCode: z.number().default(500),
      timestamp: z.string(),
    }).transform((v) => {
      return remap$(v, {
        rawResponse: "RawResponse",
        rawResponse1: "RawResponse1",
        rawResponse2: "RawResponse2",
        rawResponse3: "RawResponse3",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CouldNotBroadcast$ {
  /** @deprecated use `CouldNotBroadcast$inboundSchema` instead. */
  export const inboundSchema = CouldNotBroadcast$inboundSchema;
  /** @deprecated use `CouldNotBroadcast$outboundSchema` instead. */
  export const outboundSchema = CouldNotBroadcast$outboundSchema;
  /** @deprecated use `CouldNotBroadcast$Outbound` instead. */
  export type Outbound = CouldNotBroadcast$Outbound;
}
