/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AlreadyKnown, AlreadyKnown$ } from "./alreadyknown";
import { BadRequestException, BadRequestException$ } from "./badrequestexception";
import { CouldNotAssignNonce, CouldNotAssignNonce$ } from "./couldnotassignnonce";
import { CouldNotBroadcast, CouldNotBroadcast$ } from "./couldnotbroadcast";
import { CouldNotEstimateGasPrice, CouldNotEstimateGasPrice$ } from "./couldnotestimategasprice";
import { CouldNotFindResource, CouldNotFindResource$ } from "./couldnotfindresource";
import { CouldNotSign, CouldNotSign$ } from "./couldnotsign";
import { ExecutionWillFail, ExecutionWillFail$ } from "./executionwillfail";
import { InsufficientFunds, InsufficientFunds$ } from "./insufficientfunds";
import { InvalidGasPrice, InvalidGasPrice$ } from "./invalidgasprice";
import { NonceExpired, NonceExpired$ } from "./nonceexpired";
import { NoProviderForNetwork, NoProviderForNetwork$ } from "./noproviderfornetwork";
import {
    ReplacementGasPriceUnderpriced,
    ReplacementGasPriceUnderpriced$,
} from "./replacementgaspriceunderpriced";
import { Unknown, Unknown$ } from "./unknown";
import { UnpredictableGasLimit, UnpredictableGasLimit$ } from "./unpredictablegaslimit";
import * as z from "zod";

export type CreateTransactionTransactionManagerResponse500ResponseBody =
    | CouldNotAssignNonce
    | CouldNotBroadcast
    | CouldNotEstimateGasPrice
    | NoProviderForNetwork
    | CouldNotSign
    | Unknown;

export type CreateTransactionTransactionManagerResponseResponseBody =
    ReplacementGasPriceUnderpriced;

export type CreateTransactionTransactionManagerResponseBody = CouldNotFindResource;

export type CreateTransactionResponseBody =
    | NonceExpired
    | ExecutionWillFail
    | InvalidGasPrice
    | InsufficientFunds
    | AlreadyKnown
    | UnpredictableGasLimit
    | BadRequestException;

/** @internal */
export namespace CreateTransactionTransactionManagerResponse500ResponseBody$ {
    export type Inbound =
        | CouldNotAssignNonce$.Inbound
        | CouldNotBroadcast$.Inbound
        | CouldNotEstimateGasPrice$.Inbound
        | NoProviderForNetwork$.Inbound
        | CouldNotSign$.Inbound
        | Unknown$.Inbound;

    export type Outbound =
        | CouldNotAssignNonce$.Outbound
        | CouldNotBroadcast$.Outbound
        | CouldNotEstimateGasPrice$.Outbound
        | NoProviderForNetwork$.Outbound
        | CouldNotSign$.Outbound
        | Unknown$.Outbound;
    export const inboundSchema: z.ZodType<
        CreateTransactionTransactionManagerResponse500ResponseBody,
        z.ZodTypeDef,
        Inbound
    > = z.union([
        CouldNotAssignNonce$.inboundSchema,
        CouldNotBroadcast$.inboundSchema,
        CouldNotEstimateGasPrice$.inboundSchema,
        NoProviderForNetwork$.inboundSchema,
        CouldNotSign$.inboundSchema,
        Unknown$.inboundSchema,
    ]);
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateTransactionTransactionManagerResponse500ResponseBody
    > = z.union([
        CouldNotAssignNonce$.outboundSchema,
        CouldNotBroadcast$.outboundSchema,
        CouldNotEstimateGasPrice$.outboundSchema,
        NoProviderForNetwork$.outboundSchema,
        CouldNotSign$.outboundSchema,
        Unknown$.outboundSchema,
    ]);
}

/** @internal */
export namespace CreateTransactionTransactionManagerResponseResponseBody$ {
    export type Inbound = ReplacementGasPriceUnderpriced$.Inbound;

    export type Outbound = ReplacementGasPriceUnderpriced$.Outbound;
    export const inboundSchema: z.ZodType<
        CreateTransactionTransactionManagerResponseResponseBody,
        z.ZodTypeDef,
        Inbound
    > = ReplacementGasPriceUnderpriced$.inboundSchema;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateTransactionTransactionManagerResponseResponseBody
    > = ReplacementGasPriceUnderpriced$.outboundSchema;
}

/** @internal */
export namespace CreateTransactionTransactionManagerResponseBody$ {
    export type Inbound = CouldNotFindResource$.Inbound;

    export type Outbound = CouldNotFindResource$.Outbound;
    export const inboundSchema: z.ZodType<
        CreateTransactionTransactionManagerResponseBody,
        z.ZodTypeDef,
        Inbound
    > = CouldNotFindResource$.inboundSchema;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        CreateTransactionTransactionManagerResponseBody
    > = CouldNotFindResource$.outboundSchema;
}

/** @internal */
export namespace CreateTransactionResponseBody$ {
    export type Inbound =
        | NonceExpired$.Inbound
        | ExecutionWillFail$.Inbound
        | InvalidGasPrice$.Inbound
        | InsufficientFunds$.Inbound
        | AlreadyKnown$.Inbound
        | UnpredictableGasLimit$.Inbound
        | BadRequestException$.Inbound;

    export type Outbound =
        | NonceExpired$.Outbound
        | ExecutionWillFail$.Outbound
        | InvalidGasPrice$.Outbound
        | InsufficientFunds$.Outbound
        | AlreadyKnown$.Outbound
        | UnpredictableGasLimit$.Outbound
        | BadRequestException$.Outbound;
    export const inboundSchema: z.ZodType<CreateTransactionResponseBody, z.ZodTypeDef, Inbound> =
        z.union([
            NonceExpired$.inboundSchema,
            ExecutionWillFail$.inboundSchema,
            InvalidGasPrice$.inboundSchema,
            InsufficientFunds$.inboundSchema,
            AlreadyKnown$.inboundSchema,
            UnpredictableGasLimit$.inboundSchema,
            BadRequestException$.inboundSchema,
        ]);
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateTransactionResponseBody> =
        z.union([
            NonceExpired$.outboundSchema,
            ExecutionWillFail$.outboundSchema,
            InvalidGasPrice$.outboundSchema,
            InsufficientFunds$.outboundSchema,
            AlreadyKnown$.outboundSchema,
            UnpredictableGasLimit$.outboundSchema,
            BadRequestException$.outboundSchema,
        ]);
}
