/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    BadRequestException,
    BadRequestException$inboundSchema,
    BadRequestException$Outbound,
    BadRequestException$outboundSchema,
} from "./badrequestexception.js";
import * as z from "zod";

export type GetAllProjectMemberResponseBody = BadRequestException;

/** @internal */
export const GetAllProjectMemberResponseBody$inboundSchema: z.ZodType<
    GetAllProjectMemberResponseBody,
    z.ZodTypeDef,
    unknown
> = BadRequestException$inboundSchema;

/** @internal */
export type GetAllProjectMemberResponseBody$Outbound = BadRequestException$Outbound;

/** @internal */
export const GetAllProjectMemberResponseBody$outboundSchema: z.ZodType<
    GetAllProjectMemberResponseBody$Outbound,
    z.ZodTypeDef,
    GetAllProjectMemberResponseBody
> = BadRequestException$outboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAllProjectMemberResponseBody$ {
    /** @deprecated use `GetAllProjectMemberResponseBody$inboundSchema` instead. */
    export const inboundSchema = GetAllProjectMemberResponseBody$inboundSchema;
    /** @deprecated use `GetAllProjectMemberResponseBody$outboundSchema` instead. */
    export const outboundSchema = GetAllProjectMemberResponseBody$outboundSchema;
    /** @deprecated use `GetAllProjectMemberResponseBody$Outbound` instead. */
    export type Outbound = GetAllProjectMemberResponseBody$Outbound;
}
