/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as z from "zod";

export type SchemasSERVERNOTRESPONDINGContext = {};

export type ServerNotRespondingData = {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    context?: SchemasSERVERNOTRESPONDINGContext | undefined;
    errorCode: string;
    message: string;
    path: string;
    statusCode: number;
    timestamp: string;
};

export class ServerNotResponding extends Error {
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse?: Response | undefined;
    context?: SchemasSERVERNOTRESPONDINGContext | undefined;
    errorCode: string;
    path: string;
    statusCode: number;
    timestamp: string;

    /** The original data that was passed to this error instance. */
    data$: ServerNotRespondingData;

    constructor(err: ServerNotRespondingData) {
        super("");
        this.data$ = err;

        if (err.rawResponse != null) {
            this.rawResponse = err.rawResponse;
        }
        if (err.context != null) {
            this.context = err.context;
        }
        this.errorCode = err.errorCode;
        this.path = err.path;
        this.statusCode = err.statusCode;
        this.timestamp = err.timestamp;

        this.message =
            "message" in err && typeof err.message === "string"
                ? err.message
                : "API error occurred";

        this.name = "ServerNotResponding";
    }
}

/** @internal */
export namespace SchemasSERVERNOTRESPONDINGContext$ {
    export const inboundSchema: z.ZodType<
        SchemasSERVERNOTRESPONDINGContext,
        z.ZodTypeDef,
        unknown
    > = z.object({});

    export type Outbound = {};

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        SchemasSERVERNOTRESPONDINGContext
    > = z.object({});
}

/** @internal */
export namespace ServerNotResponding$ {
    export const inboundSchema: z.ZodType<ServerNotResponding, z.ZodTypeDef, unknown> = z
        .object({
            RawResponse: z.instanceof(Response).optional(),
            context: z.lazy(() => SchemasSERVERNOTRESPONDINGContext$.inboundSchema).optional(),
            errorCode: z.string().default("SERVER_NOT_RESPONDING"),
            message: z.string().default("Your server that receive webhook is not responding."),
            path: z.string(),
            statusCode: z.number().default(412),
            timestamp: z.string(),
        })
        .transform((v) => {
            const remapped = remap$(v, {
                RawResponse: "rawResponse",
            });

            return new ServerNotResponding(remapped);
        });

    export type Outbound = {
        RawResponse?: never | undefined;
        context?: SchemasSERVERNOTRESPONDINGContext$.Outbound | undefined;
        errorCode: string;
        message: string;
        path: string;
        statusCode: number;
        timestamp: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ServerNotResponding> = z
        .instanceof(ServerNotResponding)
        .transform((v) => v.data$)
        .pipe(
            z
                .object({
                    rawResponse: z
                        .instanceof(Response)
                        .transform(() => {
                            throw new Error("Response cannot be serialized");
                        })
                        .optional(),
                    context: z
                        .lazy(() => SchemasSERVERNOTRESPONDINGContext$.outboundSchema)
                        .optional(),
                    errorCode: z.string().default("SERVER_NOT_RESPONDING"),
                    message: z
                        .string()
                        .default("Your server that receive webhook is not responding."),
                    path: z.string(),
                    statusCode: z.number().default(412),
                    timestamp: z.string(),
                })
                .transform((v) => {
                    return remap$(v, {
                        rawResponse: "RawResponse",
                    });
                })
        );
}
