/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { BadRequestException, BadRequestException$ } from "./badrequestexception";
import { CouldNotFindResource, CouldNotFindResource$ } from "./couldnotfindresource";
import * as z from "zod";

export type UpdateRpcNetworkRpcResponseBody = CouldNotFindResource;

export type UpdateRpcResponseBody = BadRequestException;

/** @internal */
export namespace UpdateRpcNetworkRpcResponseBody$ {
    export const inboundSchema: z.ZodType<UpdateRpcNetworkRpcResponseBody, z.ZodTypeDef, unknown> =
        CouldNotFindResource$.inboundSchema;

    export type Outbound = CouldNotFindResource$.Outbound;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateRpcNetworkRpcResponseBody
    > = CouldNotFindResource$.outboundSchema;
}

/** @internal */
export namespace UpdateRpcResponseBody$ {
    export const inboundSchema: z.ZodType<UpdateRpcResponseBody, z.ZodTypeDef, unknown> =
        BadRequestException$.inboundSchema;

    export type Outbound = BadRequestException$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateRpcResponseBody> =
        BadRequestException$.outboundSchema;
}
