/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { BadRequestException, BadRequestException$ } from "./badrequestexception";
import { CouldNotFindResource, CouldNotFindResource$ } from "./couldnotfindresource";
import * as z from "zod";

export type UpdateWatcherMonitorResponseBody = CouldNotFindResource;

export type UpdateWatcherResponseBody = BadRequestException;

/** @internal */
export namespace UpdateWatcherMonitorResponseBody$ {
    export const inboundSchema: z.ZodType<UpdateWatcherMonitorResponseBody, z.ZodTypeDef, unknown> =
        CouldNotFindResource$.inboundSchema;

    export type Outbound = CouldNotFindResource$.Outbound;
    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        UpdateWatcherMonitorResponseBody
    > = CouldNotFindResource$.outboundSchema;
}

/** @internal */
export namespace UpdateWatcherResponseBody$ {
    export const inboundSchema: z.ZodType<UpdateWatcherResponseBody, z.ZodTypeDef, unknown> =
        BadRequestException$.inboundSchema;

    export type Outbound = BadRequestException$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateWatcherResponseBody> =
        BadRequestException$.outboundSchema;
}
