/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { StartonCore } from "../core.js";
import { encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../sdk/models/errors/httpclienterrors.js";
import * as errors from "../sdk/models/errors/index.js";
import { SDKError } from "../sdk/models/errors/sdkerror.js";
import { SDKValidationError } from "../sdk/models/errors/sdkvalidationerror.js";
import * as operations from "../sdk/models/operations/index.js";
import { Result } from "../sdk/types/fp.js";

/**
 * Synchronize Nonces for a wallet
 *
 * @remarks
 * Updates the stored nonce values for a wallet, synchronizing them with the current blockchain state.
 */
export async function walletResyncNonce(
  client: StartonCore,
  request: operations.ResyncNoncesWalletRequest,
  options?: RequestOptions,
): Promise<
  Result<
    operations.ResyncNoncesWalletResponse,
    | errors.ResyncNoncesWalletResponseBody
    | errors.ResyncNoncesWalletWalletResponseBody
    | errors.ResyncNoncesWalletWalletTransactionManagerResponseBody
    | errors.ResyncNoncesWalletWalletTransactionManagerResponseResponseBody
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  const parsed = safeParse(
    request,
    (value) => operations.ResyncNoncesWalletRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return parsed;
  }
  const payload = parsed.value;
  const body = null;

  const pathParams = {
    address: encodeSimple("address", payload.address, {
      explode: false,
      charEncoding: "percent",
    }),
    network: encodeSimple("network", payload.network, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/v3/kms/wallet/{address}/{network}/nonce/resync")(
    pathParams,
  );

  const headers = new Headers({
    Accept: "application/json",
  });

  const secConfig = await extractSecurity(client._options.apiKey);
  const securityInput = secConfig == null ? {} : { apiKey: secConfig };
  const context = {
    operationID: "resyncNoncesWallet",
    oAuth2Scopes: [],
    securitySource: client._options.apiKey,
  };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return requestRes;
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["400", "404", "422", "4XX", "500", "5XX"],
    retryConfig: options?.retries
      || client._options.retryConfig,
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  });
  if (!doResult.ok) {
    return doResult;
  }
  const response = doResult.value;

  const responseFields = {
    ContentType: response.headers.get("content-type")
      ?? "application/octet-stream",
    StatusCode: response.status,
    RawResponse: response,
    Headers: {},
  };

  const [result] = await M.match<
    operations.ResyncNoncesWalletResponse,
    | errors.ResyncNoncesWalletResponseBody
    | errors.ResyncNoncesWalletWalletResponseBody
    | errors.ResyncNoncesWalletWalletTransactionManagerResponseBody
    | errors.ResyncNoncesWalletWalletTransactionManagerResponseResponseBody
    | SDKError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, operations.ResyncNoncesWalletResponse$inboundSchema, {
      key: "resyncNonce",
    }),
    M.jsonErr(400, errors.ResyncNoncesWalletResponseBody$inboundSchema),
    M.jsonErr(404, errors.ResyncNoncesWalletWalletResponseBody$inboundSchema),
    M.jsonErr(
      422,
      errors
        .ResyncNoncesWalletWalletTransactionManagerResponseBody$inboundSchema,
    ),
    M.jsonErr(
      500,
      errors
        .ResyncNoncesWalletWalletTransactionManagerResponseResponseBody$inboundSchema,
    ),
    M.fail(["4XX", "5XX"]),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return result;
  }

  return result;
}
